Controllers/ActorsController.cs
using eTickets.Data;
using eTickets.Data.Services;
using eTickets.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eTickets.Controllers
{
    public class ActorsController : Controller // clasa actorscontroller mosteneste din clasa de baza controller
    {
        private readonly IActorsService _service; // trebuie sa declaram dbcontextul pentru a face legatura dintre events si db

        public ActorsController(IActorsService service) //constructor
        {
            _service = service;
        }

        public async Task<IActionResult> Index() // va afisa pagina index din Views\Actors\Index
        {
            var data = await _service.GetAllAsync();
            return View(data); //parametru data care contine informatiile din tabelul actor se va transmite paginii view
        }

        //definim actiunea de creare a unui nou actor

        public IActionResult Create() // va afisa pagina create din Views\Actors\Create
        {
            return View();
        }


        [HttpPost] // ca urmare a requestului din formularul create din pagina Views\Actors\Create

        public async Task<IActionResult> Create([Bind("FullName,ProfilePictureURL,Bio")] Actor actor) // adaugam proprietatile din view in modelul Actor
        {
            if (!ModelState.IsValid) //daca modelul nu este corect, revenim la pagina initiala
            {
                return View(actor);
            }
            await _service.AddAsync(actor); //daca e corect, adaugam actorul in db
            return RedirectToAction(nameof(Index)); //dupa adaugare, revenim la pagina initiala
        }

        //Get: Actors/Details/1
        public async Task<IActionResult> Details(int id) //parametru id
        {
            var actorDetails = await _service.GetByIdAsync(id); //verificam daca exista actor cu acel id

            if (actorDetails == null) return View("NotFound"); //daca nu exista afisam empty
            return View(actorDetails); //daca exista, afisam detaliile actorului. Pagina de tip view va prelua datele prin parametrul actorDetails
        }

        //Get: Actors/Edit
        public async Task<IActionResult> Edit(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id); //verificam daca exista id pentru actorul respectiv
            if (actorDetails == null) return View("NotFound"); //daca nu gasim id, afiseaza view not found
            return View(actorDetails); //daca gasim id, afiseaza detaliile actorului. Pagina de tip view va prelua datele prin parametrul actorDetails
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FullName,ProfilePictureURL,Bio")] Actor actor)
        {
            if (!ModelState.IsValid) //daca modelul introdus e corect
            {
                return View(actor);
            }
            await _service.UpdateAsync(id, actor); // daca este acelasi, folosim metoda UpdateAsync
            return RedirectToAction(nameof(Index)); // daca nu, redirectioneaza catre pagina index
        }

        //Get: Actors/Delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id); //verificam daca exista
            if (actorDetails == null) return View("NotFound"); //daca nu exista, afiseaza notfound view
            return View(actorDetails); //daca exista, afiseaza detaliile actorului. Pagina de tip view va prelua datele prin parametrul actorDetails
        }

        [HttpPost, ActionName("Delete")] // actiunea Delete din Views/Actors/Delete
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);
            if (actorDetails == null) return View("NotFound");

            await _service.DeleteAsync(id); // folosim metoda DeleteAsync cu parametru ID
            return RedirectToAction(nameof(Index)); //dupa stergere, ne intoarcem la pagina index
        }
    }
}
 

Controllers/CinemasController.cs
using eTickets.Data;
using eTickets.Data.Services;
using eTickets.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eTickets.Controllers
{
    public class CinemasController : Controller // clasa Cinemascontroller mosteneste din clasa de baza controller
    {
        private readonly ICinemasService _service; // trebuie sa declaram dbcontextul pentru a face legatura dintre events si db

        public CinemasController(ICinemasService service) //constructor
        {
            _service = service;
        }

        public async Task<IActionResult> Index()  // va afisa pagina index din Views\Cinemas\Index
        {
            var allCinemas = await _service.GetAllAsync();// folosim metoda GetAllAsync
            return View(allCinemas); //parametru care contine informatiile din tabelul cinema
        }


        //Get: Cinemas/Create
        // va afisa pagina create din Views\Cinemas\Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost] // ca urmare a requestului din formularul create din pagina Views\Cinemas\Create

        public async Task<IActionResult> Create([Bind("Logo,Name,Description")] Cinema cinema) // adaugam proprietatile din view in modelul Cinema
        {
            if (!ModelState.IsValid) return View(cinema); //daca modelul nu este corect, revenim la pagina initiala
            await _service.AddAsync(cinema); //daca e corect, adaugam filmul in db cu metoda AddAsync cu parametru Cinema
            return RedirectToAction(nameof(Index)); //dupa adaugare, revenim la pagina initiala
        }

        //Get: Cinemas/Details/1
        //definim actiunea Details cu parametru id
        public async Task<IActionResult> Details(int id) 
        {
            var cinemaDetails = await _service.GetByIdAsync(id);  //verificam daca exista film cu acel id
            if (cinemaDetails == null) return View("NotFound"); //daca nu gasim id, afiseaza view not found
            return View(cinemaDetails); //daca gasim id, afiseaza detaliile filmului
        }

        //Get: Cinemas/Edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var cinemaDetails = await _service.GetByIdAsync(id);
            if (cinemaDetails == null) return View("NotFound"); //daca nu exista id, afiseaza pagina NotFound din Shared Folder
            return View(cinemaDetails); // daca nu, redirectioneaza catre pagina index
        }

        [HttpPost] // actiunea Edit din Views/Cinemas/Edit
        public async Task<IActionResult> Edit(int id, [Bind("Id,Logo,Name,Description")] Cinema cinema)
        {
            if (!ModelState.IsValid) return View(cinema); //daca modelul introdus e corect
            await _service.UpdateAsync(id, cinema); //foloseste metoda update cu doi parametrii: id si cinema
            return RedirectToAction(nameof(Index)); //apoi afiseaza pagina Index
        }

        //Get: Cinemas/Delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var cinemaDetails = await _service.GetByIdAsync(id); //verificam daca exista
            if (cinemaDetails == null) return View("NotFound"); //daca nu exista, afiseaza notfound view
            return View(cinemaDetails); //daca exista, afiseaza detaliile filmului
        }

        [HttpPost, ActionName("Delete")] // actiunea Delete din Views/Cinemas/Delete
        public async Task<IActionResult> DeleteConfirm(int id)
        {
            var cinemaDetails = await _service.GetByIdAsync(id);
            if (cinemaDetails == null) return View("NotFound");

            await _service.DeleteAsync(id); // folosim metoda DeleteAsync cu parametru ID
            return RedirectToAction(nameof(Index)); //dupa stergere, ne intoarcem la pagina index
        }
    }
}

Controllers/MoviesController.cs
using eTickets.Data;
using eTickets.Data.Services;
using eTickets.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eTickets.Controllers
{
    public class MoviesController : Controller // clasa actorscontroller mosteneste din clasa de baza controller
    {
        private readonly IMoviesService _service; // trebuie sa declaram dbcontextul pentru a face legatura dintre events si db

        public MoviesController(IMoviesService service) //constructor
        {
            _service = service;
        }

        public async Task<IActionResult> Index()// returneaza o lista cu toate filmele prin folosirea metodei GetAllAsync 
        {
            var allMovies = await _service.GetAllAsync(n => n.Cinema); 
            return View(allMovies);
        }

        //implementam metoda cu numele Filter de cautare filme 
        public async Task<IActionResult> Filter(string searchString) // ia parametru stringul searchString din viewul _Layout
        {
            var allMovies = await _service.GetAllAsync(n => n.Cinema);

            if (!string.IsNullOrEmpty(searchString)) // verificam daca s-au introdus date in camp
            {
                //cauta filme dupa numele filmelor din db sau daca in descrierea lor apare acest nume, comparandu/le cu stringu-l introdus de user
                //se va afisa pagina Index cu rezultatele din varabila filteredResult

                var filteredResult = allMovies.Where(n => n.Name.Contains(searchString) || n.Description.Contains(searchString)).ToList(); 
                return View("Index", filteredResult);
            }

            return View("Index", allMovies); //daca nu au fost introduse date, afisam toate filmele
        }

        //GET: Movies/Details/1
        //definim actiunea cu numele Details care ia ca parametru Id
        public async Task<IActionResult> Details(int id)
        {
            var movieDetail = await _service.GetMovieByIdAsync(id); //variabila movieDetail primeste filmul in functie de id mentionat ca parametru in actiunea Details
            return View(movieDetail); //afisam informatiile despre film
        }

        //GET: Movies/Create
        //definim o noua actiune cu numele Create pentru a crea filme noi

        public async Task<IActionResult> Create()
        {
            var movieDropdownsData = await _service.GetNewMovieDropdownsValues(); //vom folosi metoda GetNewMovieDropdownsValues si vom crea trei liste
                                                                                    //folosim ViweBag pentru a transfera date de la controller la view

            ViewBag.Cinemas = new SelectList(movieDropdownsData.Cinemas, "Id", "Name"); // lista va lua ca parametru  variabila movieDropdownsData.Cinemas si id + numele cinemaului
            ViewBag.Producers = new SelectList(movieDropdownsData.Producers, "Id", "FullName");
            ViewBag.Actors = new SelectList(movieDropdownsData.Actors, "Id", "FullName");

            return View();
        }

        [HttpPost] // ca urmare a requestului din formularul create din pagina Views\Movies\Create
        public async Task<IActionResult> Create(NewMovieVM movie) // metoda are ca parametru modelul NewMovieVM
        {
            if (!ModelState.IsValid) // verificam modelul daca e corespunzator
            {
                var movieDropdownsData = await _service.GetNewMovieDropdownsValues();

                ViewBag.Cinemas = new SelectList(movieDropdownsData.Cinemas, "Id", "Name");
                ViewBag.Producers = new SelectList(movieDropdownsData.Producers, "Id", "FullName");
                ViewBag.Actors = new SelectList(movieDropdownsData.Actors, "Id", "FullName");

                return View(movie);
            }

            await _service.AddNewMovieAsync(movie); //daugam noul film in db
            return RedirectToAction(nameof(Index)); //dupa adaugare ne intoarcem la pagina index
        }

        //implementam metoda de modificare a filmelor
        //GET: Movies/Edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var movieDetails = await _service.GetMovieByIdAsync(id); //verificam daca exista in db
            if (movieDetails == null) return View("NotFound");//daca nu, afiseaza pagina NotFound din Shared

            var response = new NewMovieVM() //construim un raspuns la solicitarea de editare cu urmatoarele proprietati
            {
                Id = movieDetails.Id,
                Name = movieDetails.Name,
                Description = movieDetails.Description,
                Price = movieDetails.Price,
                StartDate = movieDetails.StartDate,
                EndDate = movieDetails.EndDate,
                ImageURL = movieDetails.ImageURL,
                MovieCategory = movieDetails.MovieCategory,
                CinemaId = movieDetails.CinemaId,
                ProducerId = movieDetails.ProducerId,
                ActorIds = movieDetails.Actors_Movies.Select(n => n.ActorId).ToList(), // din cauza relatiei many to many trebuie sa arata din ce tabel este preluat ID, respectiv ActorMovies, care la randul lui preia din Actors
            };

            var movieDropdownsData = await _service.GetNewMovieDropdownsValues();
            ViewBag.Cinemas = new SelectList(movieDropdownsData.Cinemas, "Id", "Name");
            ViewBag.Producers = new SelectList(movieDropdownsData.Producers, "Id", "FullName");
            ViewBag.Actors = new SelectList(movieDropdownsData.Actors, "Id", "FullName");

            return View(response);
        }

        //implementam metoda de modificare a filmelor prin POST
        [HttpPost]
        public async Task<IActionResult> Edit(int id, NewMovieVM movie)
        {
            if (id != movie.Id) return View("NotFound"); //verificam id/urile, daca nu sunt identice -> NotFound

            if (!ModelState.IsValid)
            {
                var movieDropdownsData = await _service.GetNewMovieDropdownsValues();

                ViewBag.Cinemas = new SelectList(movieDropdownsData.Cinemas, "Id", "Name");
                ViewBag.Producers = new SelectList(movieDropdownsData.Producers, "Id", "FullName");
                ViewBag.Actors = new SelectList(movieDropdownsData.Actors, "Id", "FullName");

                return View(movie);
            }

            await _service.UpdateMovieAsync(movie); //salvam filmul
            return RedirectToAction(nameof(Index)); //ne intoarcem la index
        }
    }
}

Views/Shared/NotFound.cshtml
<div class="row">
    <div class="col-md-6 offset-3">
        <h1 class="text-info">Informatia nu exista in baza de date</h1>
        <hr />
        <a class="btn btn-outline-success" asp-controller="Movies" asp-action="Index">Home Page</a>
    </div>
</div>

Views/Shared/_CreateItem.cshtml
<!-- modelul de partial view va fi folosit in toate paginile in care se poate crea o entitate-->
<!-- modelul este un string -->

@model string;

<div style="position: fixed; right: 25px; bottom: 25px;" class="text-white">
    <a asp-controller="@Model" asp-action="Create" class="btn btn-success">
        <i class="bi bi-plus-circle"></i> Add New
    </a>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html> <!--modificat layout de baza-->
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - eTickets</title> <!-- numele paginii care va aparea in bara de la browser-->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Movies" asp-action="Index">eTickets</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movies" asp-action="Index"><i class="bi bi-film"></i> Movies</a> <!-- afiseaza Movies in nav bar si trimite la Views Movies-->
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="bi bi-gear"></i> Management <!-- afiseaza Management in nav bar pentru admin  -->
                            </a>

                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-controller="Cinemas" asp-action="Index"><i class="bi bi-camera-reels"></i> Cinemas</a><!-- afiseaza optiunile pentru admin atunci cand apasa pe Management si trimite la viewsurile corespondente-->
                                <a class="dropdown-item" asp-controller="Producers" asp-action="Index"><i class="bi bi-headset"></i> Producers</a>
                                <a class="dropdown-item" asp-controller="Actors" asp-action="Index"><i class="bi bi-person-square"></i> Actors</a>
                            </div>
                        </li>
                    </ul>

                    <!-- implementam optiunea de a cauta filme-->

                    <form class="form-inline my-2 my-lg-0" asp-controller="Movies" asp-action="Filter" style="padding-right: 25px;"> 
                        <input name="searchString" type="text" class="form-control" placeholder="Search for a movie..." aria-label="Recipient's username" aria-describedby="button-addon2">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="bi bi-search"></i></button>
                    </form>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>

    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - eTickets
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>