Controllers/ActorsController.cs
using eTickets.Data;
using eTickets.Data.Services;
using eTickets.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eTickets.Controllers
{
    public class ActorsController : Controller // clasa actorscontroller mosteneste din clasa de baza controller
    {
        private readonly IActorsService _service; // trebuie sa declaram dbcontextul pentru a face legatura dintre events si db

        public ActorsController(IActorsService service) //constructor
        {
            _service = service;
        }

        public async Task<IActionResult> Index() // va afisa pagina index din Views\Actors\Index
        {
            var data = await _service.GetAllAsync();
            return View(data); //parametru data care contine informatiile din tabelul actor se va transmite paginii view
        }

        //definim actiunea de creare a unui nou actor

        public IActionResult Create() // va afisa pagina create din Views\Actors\Create
        {
            return View();
        }


        [HttpPost] // ca urmare a requestului din formularul create din pagina Views\Actors\Create

        public async Task<IActionResult> Create([Bind("FullName,ProfilePictureURL,Bio")] Actor actor) // adaugam proprietatile din view in modelul Actor
        {
            if (!ModelState.IsValid) //daca modelul nu este corect, revenim la pagina initiala
            {
                return View(actor);
            }
            await _service.AddAsync(actor); //daca e corect, adaugam actorul in db
            return RedirectToAction(nameof(Index)); //dupa adaugare, revenim la pagina initiala
        }

        //Get: Actors/Details/1
        public async Task<IActionResult> Details(int id) //parametru id
        {
            var actorDetails = await _service.GetByIdAsync(id); //verificam daca exista actor cu acel id

            if (actorDetails == null) return View("NotFound"); //daca nu exista afisam empty
            return View(actorDetails); //daca exista, afisam detaliile actorului. Pagina de tip view va prelua datele prin parametrul actorDetails
        }

        //Get: Actors/Edit
        public async Task<IActionResult> Edit(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id); //verificam daca exista id pentru actorul respectiv
            if (actorDetails == null) return View("NotFound"); //daca nu gasim id, afiseaza view not found
            return View(actorDetails); //daca gasim id, afiseaza detaliile actorului. Pagina de tip view va prelua datele prin parametrul actorDetails
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,FullName,ProfilePictureURL,Bio")] Actor actor)
        {
            if (!ModelState.IsValid) //daca modelul introdus e corect
            {
                return View(actor);
            }
            await _service.UpdateAsync(id, actor); // daca este acelasi, folosim metoda UpdateAsync
            return RedirectToAction(nameof(Index)); // daca nu, redirectioneaza catre pagina index
        }

        //Get: Actors/Delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id); //verificam daca exista
            if (actorDetails == null) return View("NotFound"); //daca nu exista, afiseaza notfound view
            return View(actorDetails); //daca exista, afiseaza detaliile actorului. Pagina de tip view va prelua datele prin parametrul actorDetails
        }

        [HttpPost, ActionName("Delete")] // actiunea Delete din Views/Actors/Delete
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);
            if (actorDetails == null) return View("NotFound");

            await _service.DeleteAsync(id); // folosim metoda DeleteAsync cu parametru ID
            return RedirectToAction(nameof(Index)); //dupa stergere, ne intoarcem la pagina index
        }
    }
}
 

Controllers/CinemasController.cs
using eTickets.Data;
using eTickets.Data.Services;
using eTickets.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eTickets.Controllers
{
    public class CinemasController : Controller // clasa Cinemascontroller mosteneste din clasa de baza controller
    {
        private readonly ICinemasService _service; // trebuie sa declaram dbcontextul pentru a face legatura dintre events si db

        public CinemasController(ICinemasService service) //constructor
        {
            _service = service;
        }

        public async Task<IActionResult> Index()  // va afisa pagina index din Views\Cinemas\Index
        {
            var allCinemas = await _service.GetAllAsync();// folosim metoda GetAllAsync
            return View(allCinemas); //parametru care contine informatiile din tabelul cinema
        }


        //Get: Cinemas/Create
        // va afisa pagina create din Views\Cinemas\Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost] // ca urmare a requestului din formularul create din pagina Views\Cinemas\Create

        public async Task<IActionResult> Create([Bind("Logo,Name,Description")] Cinema cinema) // adaugam proprietatile din view in modelul Cinema
        {
            if (!ModelState.IsValid) return View(cinema); //daca modelul nu este corect, revenim la pagina initiala
            await _service.AddAsync(cinema); //daca e corect, adaugam filmul in db cu metoda AddAsync cu parametru Cinema
            return RedirectToAction(nameof(Index)); //dupa adaugare, revenim la pagina initiala
        }

        //Get: Cinemas/Details/1
        //definim actiunea Details cu parametru id
        public async Task<IActionResult> Details(int id) 
        {
            var cinemaDetails = await _service.GetByIdAsync(id);  //verificam daca exista film cu acel id
            if (cinemaDetails == null) return View("NotFound"); //daca nu gasim id, afiseaza view not found
            return View(cinemaDetails); //daca gasim id, afiseaza detaliile filmului
        }

        //Get: Cinemas/Edit/1
        public async Task<IActionResult> Edit(int id)
        {
            var cinemaDetails = await _service.GetByIdAsync(id);
            if (cinemaDetails == null) return View("NotFound"); //daca nu exista id, afiseaza pagina NotFound din Shared Folder
            return View(cinemaDetails); // daca nu, redirectioneaza catre pagina index
        }

        [HttpPost] // actiunea Edit din Views/Cinemas/Edit
        public async Task<IActionResult> Edit(int id, [Bind("Id,Logo,Name,Description")] Cinema cinema)
        {
            if (!ModelState.IsValid) return View(cinema); //daca modelul introdus e corect
            await _service.UpdateAsync(id, cinema); //foloseste metoda update cu doi parametrii: id si cinema
            return RedirectToAction(nameof(Index)); //apoi afiseaza pagina Index
        }

        //Get: Cinemas/Delete/1
        public async Task<IActionResult> Delete(int id)
        {
            var cinemaDetails = await _service.GetByIdAsync(id); //verificam daca exista
            if (cinemaDetails == null) return View("NotFound"); //daca nu exista, afiseaza notfound view
            return View(cinemaDetails); //daca exista, afiseaza detaliile filmului
        }

        [HttpPost, ActionName("Delete")] // actiunea Delete din Views/Cinemas/Delete
        public async Task<IActionResult> DeleteConfirm(int id)
        {
            var cinemaDetails = await _service.GetByIdAsync(id);
            if (cinemaDetails == null) return View("NotFound");

            await _service.DeleteAsync(id); // folosim metoda DeleteAsync cu parametru ID
            return RedirectToAction(nameof(Index)); //dupa stergere, ne intoarcem la pagina index
        }
    }
}

Controllers/ProducersController.cs
using eTickets.Data;
using eTickets.Data.Services;
using eTickets.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace eTickets.Controllers
{
    public class ProducersController : Controller
    {
        private readonly IProducersService _service; // trebuie sa declaram dbcontextul pentru a face legatura dintre events si db

        public ProducersController(IProducersService service) //constructor
        {
            _service = service;
        }

        public async Task<IActionResult> Index()
        { 
            var allProducers = await _service.GetAllAsync();
            return View(allProducers);
        }

        //GET: producerscontroller/details/1 = id
        //definim o noua actiune = Details care va afisa informatii despre producatorul selectat

        public async Task<IActionResult> Details(int id)
        {
            var producerDetails = await _service.GetByIdAsync(id); // verificam daca producatorul exista in db
            if (producerDetails == null) return View("NotFound"); //daca nu exista, afiseaza fereastra Notfound din Folderul Shared
            return View(producerDetails); //daca exista, afiseaza informatiile despre producator
        }


        //GET: producers/create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost] // ca urmare a requestului din formularul create din pagina Views\Producers\Create
        public async Task<IActionResult> Create([Bind("ProfilePictureURL,FullName,Bio")] Producer producer) // adaugam proprietatile din view in modelul Producer
        {
            if (!ModelState.IsValid) return View(producer); //daca modelul nu este corect, revenim la pagina initiala

            await _service.AddAsync(producer); //daca e corect, adaugam producatorul in db
            return RedirectToAction(nameof(Index)); //dupa adaugare, revenim la pagina initiala
        }


        //GET: producers/edit/1
        //definim actiunea de modificare
        public async Task<IActionResult> Edit(int id)
        {
            var producerDetails = await _service.GetByIdAsync(id); //verificam daca producatorul exista in db
            if (producerDetails == null) return View("NotFound"); //daca nu gasim id, afiseaza view not found din Shared Folder
            return View(producerDetails);//daca gasim id, afiseaza detaliile producatorului
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ProfilePictureURL,FullName,Bio")] Producer producer)
        {
            if (!ModelState.IsValid) return View(producer);

            if (id == producer.Id) // verificam ID din db cu cel din request
            {
                await _service.UpdateAsync(id, producer); // daca este acelasi, folosim metoda UpdateAsync
                return RedirectToAction(nameof(Index)); // daca nu, redirectioneaza catre pagina index
            }
            return View(producer);
        }

        //GET: producers/delete/1
        //definim actiunea delete

        public async Task<IActionResult> Delete(int id)
        {
            var producerDetails = await _service.GetByIdAsync(id); //verificam daca exista id respectiv
            if (producerDetails == null) return View("NotFound"); //daca nu exista, afiseaza notfound view
            return View(producerDetails); //daca exista, afiseaza detaliile producatorului
        }

        [HttpPost, ActionName("Delete")] // actiunea Delete din Views/Producers/Delete
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var producerDetails = await _service.GetByIdAsync(id);
            if (producerDetails == null) return View("NotFound");

            await _service.DeleteAsync(id); // folosim metoda DeleteAsync cu parametru ID
            return RedirectToAction(nameof(Index)); //dupa stergere, ne intoarcem la pagina index
        }
    }
}

Views/Movies/Create.cshtml
@model NewMovieVM 
    <!-- propireatile vor fi preluate din clasa Data\ViewModels\NewMovieVM-->
@using eTickets.Data;

@{
    ViewData["Title"] = "Create a new movie"; // numele paginii
}

<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4>Create a new movie</h4>
        </p>

        <div class="row">
            <div class="col-md-8 offset-2">

                <!--   inseram formularul de creare a filmului pe doua coloane-->

                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div> <!-- informatiile introduse trebuie sa corespunda proprietatilor din model     -->

                    <div class="row">

                        <!--   prima coloana-->

                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Name" class="control-label"></label>
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="StartDate" class="control-label"></label>
                                <input asp-for="StartDate" type="date" class="form-control" />
                                <span asp-validation-for="StartDate" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="EndDate" class="control-label"></label>
                                <input asp-for="EndDate" type="date" class="form-control" />
                                <span asp-validation-for="EndDate" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Price" class="control-label"></label>
                                <input asp-for="Price" type="number" class="form-control" />
                                <span asp-validation-for="Price" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ImageURL" class="control-label"></label>
                                <input asp-for="ImageURL" class="form-control" />
                                <span asp-validation-for="ImageURL" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">

                            <!--   a doua coloana-->

                            <div class="form-group">
                                <label asp-for="CinemaId" class="control-label"></label>

                                <!-- va prelua datele din actiunea Create din MoviesController care contine o metoda de a afisa cinemaurile din db  -->
                                <select asp-for="CinemaId" class="form-control" asp-items="ViewBag.Cinemas"></select>
                                <span asp-validation-for="CinemaId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="MovieCategory" class="control-label"></label>

                                <!-- se vor afisa categoriile posibile sub forma unei liste folsin o metoda html ca va prelua datele din Data\Enums\ clasa MovieCategory-->
                                <select asp-for="MovieCategory" class="form-control" asp-items="Html.GetEnumSelectList<MovieCategory>()"></select>
                                <span asp-validation-for="MovieCategory" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ProducerId" class="control-label"></label>

                                <!-- va prelua datele din actiunea Create din MoviesController care contine o metoda de a afisa producatorii din db  -->
                                <select asp-for="ProducerId" class="form-control" asp-items="ViewBag.Producers"></select>
                                <span asp-validation-for="ProducerId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ActorIds" class="control-label"></label>
                                <!-- va prelua datele din actiunea Create din MoviesController care contine o metoda de a afisa actorii din db  -->
                                <select asp-for="ActorIds" class="form-control" asp-items="ViewBag.Actors" multiple></select>
                                <span asp-validation-for="ActorIds" class="text-danger"></span>
                            </div>
                        </div>

                        <!--   sectiunea despre descrierea filmului -->
                        <div class="col-md-12">
                            <div class="form-group">
                                <label asp-for="Description" class="control-label"></label>
                                <textarea asp-for="Description" class="form-control"></textarea>
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                        </div>
                    </div>

                    <!--   previzualizareaa imaginii filmului folosind un script-->

                    <div class="col-md-4 offset-4 text-center">
                        <img width="100" id="ImageUrlPreview" />
                    </div>

                    <!--   cream butoanele Create pentru formular si Show all care va trimite la pagina Index din Views\Movies-->
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show all</a>
                    </div>

                </form>

            </div>
        </div>

    </div>
</div>

<!--   crearea scriptului pentru precizualizarea imaginii filmului -->
<!--   cand input fiekdul cu id = ImageURL se schimba, rulam o functie care va prelua valoarea din ImageUrlPreview si o va afisa -->

@section Scripts{
    <script>
        $("#ImageURL").on("change", function () {
            var output = document.getElementById("ImageUrlPreview");
            output.src = $(this).val();
        })
    </script>
}

Views/Movies/Details.cshtml
@model Movie

@{
    ViewData["Title"] = "Movie details"; // titlul paginii
}

<div class="row">
    <div class="col-md-8 offset-2">
        <div class="card mb-12">
            <div class="row g-0">
                <div class="col-md-12">
                    <div class="card-header text-white bg-info">
                        <p class="card-text">
                            <h5 class="card-title"> <!-- numele filmului-->
                                @Model.Name
                            </h5>
                        </p>
                    </div>
                </div>
                <div class="col-md-4">
                    <img src="@Model.ImageURL" width="100%" alt="@Model.Name">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <p class="card-text">@Model.Description</p>
                        <p class="card-text">
                            <b>Cinema: </b>

                            <!-- inseream o actiune catre pagina care contine informatiile despre cinema-->
                            <a asp-controller="Cinemas" asp-action="Details" asp-route-id="@Model.CinemaId">
                                @Model.Cinema.Name
                            </a>
                        </p>
                        <p class="card-text">
                            <b>Producer: </b>

                            <!-- inseram o actiune catre pagina care contine informatiile despre producator-->
                            <a asp-controller="Producers" asp-action="Details" asp-route-id="@Model.ProducerId">
                                @Model.Producer.FullName
                            </a>
                            <!--  sectiunea cu informatii despre film-->
                        </p>
                        <p class="card-text"><b>Category: </b>@Model.MovieCategory</p>
                        <p class="card-text"><b>Start Date: </b>@Model.StartDate.ToString("dd MMM yy")</p>
                        <p class="card-text"><b>End Date: </b>@Model.EndDate.ToString("dd MMM yy")</p>
                        <p class="card-text ">
                            <b>Status: </b>
                            @if (DateTime.Now >= Model.StartDate && DateTime.Now <= Model.EndDate)
                            {
                                <span class="badge bg-success text-white">AVAILABLE</span>
                            }
                            else if (DateTime.Now > Model.EndDate)
                            {
                                <span class="badge bg-danger text-white">EXPIRED</span>
                            }
                            else
                            {
                                <span class="badge bg-primary text-white">UPCOMING</span>
                            }
                        </p>
                        <p class="card-text">
                            <b>Actors: </b>
                            <hr />
                            <div class="row">

                                <!-- sectiunea cu informatii despre actori -->
                                <!-- folosim un foreach loop pentru a afisa date cu toti actorii care apar in film -->

                                @foreach (var actor in Model.Actors_Movies)
                                {
                                <div class="column text-center">
                                    <img class="border-info rounded-circle" src="@actor.Actor.ProfilePictureURL" style="max-width: 150px" />
                                    <br />

                                    <!-- inseram o actiune catre pagina care contine informatii despre actor la apasarea pe nume -->

                                    <a asp-controller="Actors" asp-action="Details" asp-route-id="@actor.ActorId">@actor.Actor.FullName</a>
                                </div>
                                }
                            </div>
                        </p>

                    </div>
                </div>
                <div class="col-md-12">
                    <div class="card-footer">
                        <p class="card-text">
                            <!-- buton catre pagina index -->
                            <a class="btn btn-outline-primary float-right" asp-action="Index">
                                Back to List
                            </a>
                            <a class="btn btn-success text-white"><i class="bi bi-cart-plus"></i> Add to Cart (Price @Model.Price.ToString("c"))</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Views/Movies/Edit.cshtml
@model NewMovieVM
@using eTickets.Data;

@{
    ViewData["Title"] = "Update movie";
}

<div class="row">
    <div class="col-md-8 offset-2">
        <p>
            <h4>Update movie</h4>
        </p>

        <div class="row">
            <div class="col-md-8 offset-2">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="Name" class="control-label"></label>
                                <input asp-for="Name" class="form-control" />
                                <span asp-validation-for="Name" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="StartDate" class="control-label"></label>
                                <input asp-for="StartDate" type="date" class="form-control" />
                                <span asp-validation-for="StartDate" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="EndDate" class="control-label"></label>
                                <input asp-for="EndDate" type="date" class="form-control" />
                                <span asp-validation-for="EndDate" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="Price" class="control-label"></label>
                                <input asp-for="Price" type="number" class="form-control" />
                                <span asp-validation-for="Price" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ImageURL" class="control-label"></label>
                                <input asp-for="ImageURL" class="form-control" />
                                <span asp-validation-for="ImageURL" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <label asp-for="CinemaId" class="control-label"></label>
                                <select asp-for="CinemaId" class="form-control" asp-items="ViewBag.Cinemas"></select>
                                <span asp-validation-for="CinemaId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="MovieCategory" class="control-label"></label>
                                <select asp-for="MovieCategory" class="form-control" asp-items="Html.GetEnumSelectList<MovieCategory>()"></select>
                                <span asp-validation-for="MovieCategory" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ProducerId" class="control-label"></label>
                                <select asp-for="ProducerId" class="form-control" asp-items="ViewBag.Producers"></select>
                                <span asp-validation-for="ProducerId" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <label asp-for="ActorIds" class="control-label"></label>
                                <select asp-for="ActorIds" class="form-control" asp-items="ViewBag.Actors" multiple></select>
                                <span asp-validation-for="ActorIds" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <label asp-for="Description" class="control-label"></label>
                                <textarea asp-for="Description" class="form-control"></textarea>
                                <span asp-validation-for="Description" class="text-danger"></span>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-4 offset-4 text-center">
                        <img width="100" id="ImageUrlPreview" />
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Update" class="btn btn-outline-success float-right" />
                        <a class="btn btn-outline-secondary" asp-action="Index">Show all</a>
                    </div>

                </form>

            </div>
        </div>

    </div>
</div>

@section Scripts{
    <script>
        $(document).ready(function () {
            var output = document.getElementById("ImageUrlPreview");
            output.src = $("#ImageURL").val();
        });
        $("#ImageURL").on("change", function () {
            var output = document.getElementById("ImageUrlPreview");
            output.src = $(this).val();
        })
    </script>
}